FROM ubuntu:latest
LABEL maintainer="anna.cruz@gmail.com"

RUN apt update && apt install openssh-server sudo -y

RUN useradd -rm -d /home/ubuntu -s /bin/bash -g root -G sudo -u 1000 node

RUN echo 'node:node1234' | chpasswd

RUN service ssh start

EXPOSE 2222

CMD ["/usr/sbin/sshd", "-D"]

