---
- name: Install docker
  hosts: all

  tasks:
    - name: Install basic package
      homebrew_cask: name=docker state=present
    
    - name: Install docker-compose
      homebrew: name=docker-compose state=present
