---
- name: Configure Neovim
  hosts: all
  vars:
    neovim_config_repo: https://github.com/annacruz/nvim.git
    neovim_config_dir: ~/.config/nvim
    apps:
      - ripgrep
      - fd
    fonts:
      - font-plemol-jp
      - font-plemol-jp-nf
      - font-plemol-jp-hs

  tasks:
    - name: Clone configuration
      git: repo={{ neovim_config_repo }} dest={{ neovim_config_dir }} recursive=yes force=yes

    - name: Install necessary packages (plugins requirements)
      community.general.homebrew:
        name: "{{ apps }}"
      when: ansible_os_family == "Darwin"

    # - name: Install necessary packages (plugins requirements) - Debian/Ubuntu
    #   ansible.builtin.package:
    #     name: "{{ apps }}"
    #   when: ansible_os_family == "Debian"

    - name: Install nice fonts
      community.general.homebrew:
        name: "{{ fonts }}"
      when: ansible_os_family == "Darwin"

    # - name: Install nice fonts
    #   ansible.bultin.package:
    #     name: "{{ fonts }}"
    #   when: ansible_os_family == "Debian"
