- name: Install base apps
  hosts: all
  vars:
    taps:
      - homebrew/cask-fonts
      - nexeck/homebrew-tmuxinator

    apps:
      - coreutils
      - git
      - jq
      - lazydocker
      - passenger
      - htop
      - httpie
      - neovim
      - nginx
      - the_silver_searcher
      - tig
      - tmux
      - wget
      - yarn
      - node
      - sqlite
      - asdf

    cask_apps:
      - iterm2
      - rectangle
      - spotify
      - keka
      - visual-studio-code

    fonts:
      - font-inconsolata
      - font-inconsolata-for-powerline
      - font-hack-nerd-font
      - font-fira-code-nerd-font

    extra:
      - nexeck/homebrew-tmuxinator/tmuxinator 

  tasks:
    - name: Add homebrew taps
      community.general.homebrew_tap: 
        name: "{{ taps }}"

    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ apps }}"
        state: latest

    - name: Install homebrew cask packages
      community.general.homebrew_cask:
        name: "{{ cask_apps }}"
        state: latest

    - name: Install fonts
      community.general.homebrew:
        name: "{{ fonts }}"
        state: latest

    - name: Install extra
      community.general.homebrew:
        name: "{{ extra }}"
        state: latest

