- name: Install base apps
  hosts: all
  vars:
    apps:
      - mysql
      - launchdns

  tasks:
    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ apps }}"
        state: latest

