- name: Install base apps
  hosts: all
  vars:
    apps:
      - asdf
      - bat
      - coreutils
      - docker
      - fd
      - ffmpeg
      - gcc
      - git
      - htop
      - httpie
      - jq
      - lazydocker
      - lazygit
      - lsd
      - neovim
      - nginx
      - node
      - passenger
      - sqlite
      - tig
      - tldr
      - tmux
      - wget
      - yarn
      - zsh

    cask_apps:
      - iterm2
      - rectangle
      - spotify
      - keka
      - visual-studio-code

    fonts:
      - font-inconsolata
      - font-inconsolata-for-powerline
      - font-hack-nerd-font
      - font-fira-code-nerd-font
      - font-plemol-jp
      - font-plemol-jp-nf
      - font-plemol-jp-hs

  tasks:
    - name: Install homebrew packages
      community.general.homebrew:
        name: "{{ apps }}"
        state: latest

    - name: Install homebrew cask packages
      community.general.homebrew_cask:
        name: "{{ cask_apps }}"
        state: latest

    - name: Install fonts
      community.general.homebrew_cask:
        name: "{{ fonts }}"
        state: latest
