---
- name: Vim setup
  hosts: all
  vars:
    vim_config_repo: https://github.com/annacruz/vimrc
    vim_folder: ~/.vim
    vim_plug_file: https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
    vim_config_dir: ~/vim-config
    vimrc_file: ~/vim-config/vimrc

  tasks:  
    - name: Clone configuration
      git: repo={{ vim_config_repo }} dest={{ vim_config_dir }} recursive=yes version=master force=yes

    - name: Install vim-plug
      shell: curl -fLo ~/.vim/autoload/plug.vim --create-dirs {{ vim_plug_file }}

    - name: Configure vim alias
      lineinfile:
        path: ~/.zshrc
        line: alias vim="vim -u {{ vimrc_file }}"

    - name: Install vim plugins
      shell: vim -E -s -c "source {{ vimrc_file }}" -c PluginInstall -c qa
